[package]
name = "imacodr/PodKit"
version = "0.1.0"
authors = [
    "Sam P <me@imacodr.com>"
]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
    "/modules/Icons"
]

[dependencies]
Fusion = "elttob/fusion@0.2.0"
Koute = "koterahq/koute@1.0.3"