[package]
name = "imacodr/Construct"
description = "A UI Framework for Roblox based on Fusion."
version = "0.0.1-alpha"
authors = [
    "Sam P <me@imacodr.com>"
]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
    "/modules/Icons"
]

[dependencies]
Fusion = "elttob/fusion@0.2.0"