[package]
name = "imacodr/construct"
description = "The ultimate component library for Fusion with next level theming capabilities."
version = "0.0.14-alpha"
authors = [
    "Sam P <me@imacodr.com>"
]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
    "modules/Icons"
]

[dependencies]
Fusion = "elttob/fusion@0.2.0"