--!strict

return {
    unknownError = "Unknown error: %s",
    wrongComponentPropertyType = "Component property '%s' is of type '%s', but should be of type '%s'.",
    wrongComponentPropertyType2 = "Component property '%s' is of type '%s', but should be of type '%s' or '%s'.",
    invalidClassWhenAssimilating = "Invalid class '%s' when assimilating '%s'. This component can only assimilate the following: '%s'",
    themeManagerCatch = "themeManager Error: '%s'",
    checkPositionCatch = "checkPosition Error: '%s'",
    checkSizeCatch = "checkSize Error: '%s'",
    checkAnchorPointCatch = "checkAnchorPoint Error: '%s'",
    toastUUIDCatch = "useToast was not able to generate a unique ID using Roblox's HttpService (most likely for Roblox Services being unavailable).\n\n Proceeding with number ToastId.\n\n Full Error: '%s'",
}
