[package]
name = "imacodr/destructcons"
description = "Collection of Icons to use with the Construct library"
version = "0.0.1-alpha"
authors = [
    "Sam P <me@imacodr.com>"
]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"